---
path: github.com/mc0/okq
deps:
    - loc: github.com/fzzy/radix/redis
    - loc: github.com/mediocregopher/flagconfig
    - loc: github.com/mediocregopher/pubsubch
    - loc: github.com/stretchr/testify
